#!/usr/bin/env bash

code --uninstall-extension alefragnani.project-manager
code --uninstall-extension christian-kohler.path-intellisense
code --uninstall-extension CoenraadS.bracket-pair-colorizer
code --uninstall-extension donjayamanne.githistory
code --uninstall-extension eg2.tslint
code --uninstall-extension formulahendry.code-runner
code --uninstall-extension esbenp.prettier-vscode
code --uninstall-extension infinity1207.angular2-switcher
code --uninstall-extension jakethashi.vscode-angular2-emmet
code --uninstall-extension joelday.docthis
code --uninstall-extension johnpapa.Angular2
code --uninstall-extension ms-vscode.sublime-keybindings
code --uninstall-extension msjsdiag.debugger-for-chrome
code --uninstall-extension natewallace.angular2-inline
code --uninstall-extension PeterJausovec.vscode-docker
code --uninstall-extension vscjava.vscode-java-pack
code --uninstall-extension robertohuertasm.vscode-icons
code --uninstall-extension Shan.code-settings-sync
code --uninstall-extension silverlakesoftware.searchdocsets-vscode
code --uninstall-extension swyphcosmo.spellchecker
code --uninstall-extension Telerik.nativescript
code --uninstall-extension Thavarajan.ionic2
code --uninstall-extension vsmobile.cordova-tools
code --uninstall-extension WallabyJs.quokka-vscode
code --uninstall-extension wesbos.theme-cobalt2
code --uninstall-extension Arjun.swagger-viewer
code --uninstall-extension ms-vscode.csharp
code --uninstall-extension ms-vscode.cpptools
code --uninstall-extension kalitaalexey.vscode-rust
code --uninstall-extension joaompinto.asciidoctor-vscode
code --uninstall-extension wayou.vscode-todo-highlight
code --uninstall-extension ms-python.python
code --uninstall-extension dcortes92.FreeMarker
code --uninstall-extension sasxa-net.angular-gui
code --uninstall-extension pnp.polacode
code --uninstall-extension eamodio.gitlens

code --install-extension alefragnani.project-manager
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension donjayamanne.githistory
code --install-extension eg2.tslint
code --install-extension formulahendry.code-runner
code --install-extension esbenp.prettier-vscode
code --install-extension infinity1207.angular2-switcher
code --install-extension jakethashi.vscode-angular2-emmet
code --install-extension joelday.docthis
code --install-extension johnpapa.Angular2
code --install-extension ms-vscode.sublime-keybindings
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension natewallace.angular2-inline
code --install-extension PeterJausovec.vscode-docker
code --install-extension vscjava.vscode-java-pack
code --install-extension robertohuertasm.vscode-icons
code --install-extension Shan.code-settings-sync
code --install-extension silverlakesoftware.searchdocsets-vscode
code --install-extension swyphcosmo.spellchecker
code --install-extension Telerik.nativescript
code --install-extension Thavarajan.ionic2
code --install-extension vsmobile.cordova-tools
code --install-extension WallabyJs.quokka-vscode
code --install-extension wesbos.theme-cobalt2
code --install-extension Arjun.swagger-viewer
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.cpptools
code --install-extension kalitaalexey.vscode-rust
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension ms-python.python
code --install-extension dcortes92.FreeMarker
code --install-extension sasxa-net.angular-gui
code --install-extension pnp.polacode
code --install-extension eamodio.gitlens
